name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    convert-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                cache: 'pip'
            - run: pip install odfpy pyhtml2pdf
            - run: mkdir -p html
            - run: mkdir -p pdf
            - run: odf2xhtml odt/prova.odt | tee html/prova.html
            - uses: fifsky/html-to-pdf-action@master
              with:
                htmlFile: ./html/prova.html
                outputFile: ./pdf/prova.pdf
                pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
            - uses: stefanzweifel/git-auto-commit-action@v5
